const actionTypes = {
  POSTS_REQUEST: 'POSTS_REQUEST',
  POSTS_REQUEST_SUCCESS: 'POSTS_REQUEST_SUCCESS',
  POSTS_REQUEST_FAILURE: 'POSTS_REQUEST_FAILURE',
  POST_FILTER_BY_SUBREADIT_REQUEST: 'POST_FILTER_BY_SUBREADIT_REQUEST',
  POST_FILTER_BY_SUBREADIT_REQUEST_SUCCESS: 'POST_FILTER_BY_SUBREADIT_REQUEST_SUCCESS',
  POST_FILTER_BY_SUBREADIT_REQUEST_FAILURE: 'POST_FILTER_BY_SUBREADIT_REQUEST_FAILURE',
  POST_UP_VOTE_REQUEST: 'POST_UP_VOTE_REQUEST',
  POST_UP_VOTE_REQUEST_SUCCESS: 'POST_UP_VOTE_REQUEST_SUCCESS',
  POST_UP_VOTE_REQUEST_FAILURE: 'POST_UP_VOTE_REQUEST_FAILURE',
  POST_DOWN_VOTE_REQUEST: 'POST_DOWN_VOTE_REQUEST',
  POST_DOWN_VOTE_REQUEST_SUCCESS: 'POST_DOWN_VOTE_REQUEST_SUCCESS',
  POST_DOWN_VOTE_REQUEST_FAILURE: 'POST_DOWN_VOTE_REQUEST_FAILURE'
};

export default actionTypes;