const actionTypes = {
  POSTS_REQUEST: 'POSTS_REQUEST',
  POSTS_REQUEST_SUCCESS: 'POSTS_REQUEST_SUCCESS',
  POSTS_REQUEST_FAILURE: 'POSTS_REQUEST_FAILURE',
  POSTS_FILTER_BY_SUBREADIT_REQUEST: 'POSTS_FILTER_BY_SUBREADIT_REQUEST',
  POSTS_FILTER_BY_SUBREADIT_REQUEST_SUCCESS: 'POSTS_FILTER_BY_SUBREADIT_REQUEST_SUCCESS',
  POSTS_FILTER_BY_SUBREADIT_REQUEST_FAILURE: 'POSTS_FILTER_BY_SUBREADIT_REQUEST_FAILURE',
  POSTS_FILTER_BY_USERNAME_REQUEST: 'POSTS_FILTER_BY_USERNAME_REQUEST',
  POSTS_FILTER_BY_USERNAME_REQUEST_SUCCESS: 'POSTS_FILTER_BY_USERNAME_REQUEST_SUCCESS',
  POSTS_FILTER_BY_USERNAME_REQUEST_FAILURE: 'POSTS_FILTER_BY_USERNAME_REQUEST_FAILURE',
  POSTS_CANCEL_REQUEST: 'POSTS_CANCEL_REQUEST',
  POSTS_CANCELLED_REQUEST: 'POSTS_CANCELLED_REQUEST',
  POSTS_CLEAR_POP_UP: 'POSTS_CLEAR_POP_UP'
};

export default actionTypes;