const actionTypes = {
  CREATE_POST_REQUEST: 'CREATE_POST_REQUEST',
  CREATE_POST_REQUEST_SUCCESS: 'CREATE_POST_REQUEST_SUCCESS',
  CREATE_POST_REQUEST_FAILURE: 'CREATE_POST_REQUEST_FAILURE',
  READ_POST_REQUEST: 'READ_POST_REQUEST',
  READ_POST_REQUEST_SUCCESS: 'READ_POST_REQUEST_SUCCESS',
  READ_POST_REQUEST_FAILURE: 'READ_POST_REQUEST_FAILURE',
  CRUD_CANCEL_REQUEST: 'CRUD_CANCEL_REQUEST',
  CRUD_CANCELLED_REQUEST: 'CRUD_CANCELLED_REQUEST'
};

export default actionTypes;