const actionTypes = {
  CREATE_POST_REQUEST: 'CREATE_POST_REQUEST',
  CREATE_POST_REQUEST_SUCCESS: 'CREATE_POST_REQUEST_SUCCESS',
  CREATE_POST_REQUEST_FAILURE: 'CREATE_POST_REQUEST_FAILURE',
};

export default actionTypes;