const actionTypes = {
  VOTE_UP_REQUEST: 'VOTE_UP_REQUEST',
  VOTE_UP_REQUEST_SUCCESS: 'VOTE_UP_REQUEST_SUCCESS',
  VOTE_UP_REQUEST_FAILURE: 'VOTE_UP_REQUEST_FAILURE',
  VOTE_DOWN_REQUEST: 'VOTE_DOWN_REQUEST',
  VOTE_DOWN_REQUEST_SUCCESS: 'VOTE_DOWN_REQUEST_SUCCESS',
  VOTE_DOWN_REQUEST_FAILURE: 'VOTE_DOWN_REQUEST_FAILURE',
  VOTES_CHECK_REQUEST: 'VOTES_CHECK_REQUEST',
  VOTES_CHECK_REQUEST_SUCCESS: 'VOTES_CHECK_REQUEST_SUCCESS',
  VOTES_CHECK_REQUEST_FAILURE: 'VOTES_CHECK_REQUEST_FAILURE'
};

export default actionTypes;