const actionTypes = {
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_REQUEST_SUCCESS: 'SIGN_UP_REQUEST_SUCCESS',
  SIGN_UP_REQUEST_FAILURE: 'SIGN_UP_REQUEST_FAILURE',
  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN_REQUEST_SUCCESS: 'SIGN_IN_REQUEST_SUCCESS',
  SIGN_IN_REQUEST_FAILURE: 'SIGN_IN_REQUEST_FAILURE',
  AUTH_CLEAR_POP_UP: 'AUTH_CLEAR_POP_UP',
  SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
  SIGN_OUT_REQUEST_SUCCESS: 'SIGN_OUT_REQUEST_SUCCESS',
  SIGN_OUT_REQUEST_FAILURE: 'SIGN_OUT_REQUEST_FAILURE',
}

export default actionTypes