const actionTypes = {
  ADD_COMMENT_REQUEST: 'ADD_COMMENT_REQUEST',
  ADD_COMMENT_REQUEST_SUCCESS: 'ADD_COMMENT_REQUEST_SUCCESS',
  ADD_COMMENT_REQUEST_FAILURE: 'ADD_COMMENT_REQUEST_FAILURE'
}

export default actionTypes;