const actionTypes = {
  CATEGORIES_REQUEST: 'CATEGORIES_REQUEST',
  CATEGORIES_REQUEST_SUCCESS: 'CATEGORIES_REQUEST_SUCCESS',
  CATEGORIES_REQUEST_FAILURE: 'CATEGORIES_REQUEST_FAILURE'
};

export default actionTypes;