const actionTypes = {
  SUB_READIT_LISTS_REQUEST: 'SUB_READIT_LISTS_REQUEST',
  SUB_READIT_LISTS_REQUEST_SUCCESS: 'SUB_READIT_LISTS_REQUEST_SUCCESS',
  SUB_READIT_LISTS_REQUEST_FAILURE: 'SUB_READIT_LISTS_REQUEST_FAILURE',
  SUB_READIT_REQUEST: 'SUB_READIT_REQUEST',
  SUB_READIT_REQUEST_SUCCESS: 'SUB_READIT_REQUEST_SUCCESS',
  SUB_READIT_REQUEST_FAILURE: 'SUB_READIT_REQUEST_FAILURE',
  SUB_READIT_CANCEL_REQUEST: 'SUB_READIT_CANCEL_REQUEST',
  SUB_READIT_CANCELLED_REQUEST: 'SUB_READIT_CANCELLED_REQUEST'
};

export default actionTypes;