const actionTypes = {
  SUB_READIT_REQUEST: 'SUB_READIT_REQUEST',
  SUB_READIT_REQUEST_SUCCESS: 'SUB_READIT_REQUEST_SUCCESS',
  SUB_READIT_REQUEST_FAILURE: 'SUB_READIT_REQUEST_FAILURE'
};

export default actionTypes;